docker_ce_version: "3:27.5.1-1.fc41"
docker_ce_cli_version: "1:27.5.1-1.fc41"
containerd_version: "1.7.25-3.1.fc41"
docker_buildx_version: "0.20.0-1.fc41"
docker_compose_version: "2.32.4-1.fc41"
architecture: amd64