---
# tasks/main.yml
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create the /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to Apt sources
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: |
      deb [arch={{ architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable
    create: yes

- name: Update apt cache after adding Docker repository
  apt:
    update_cache: yes
    
- name: Install Docker and related components
  apt:
    name:
      - "docker-ce={{ docker_ce_version }}"
      - "docker-ce-cli={{ docker_ce_cli_version }}"
      - "containerd.io={{ containerd_version }}"
      - "docker-buildx-plugin={{ docker_buildx_version }}"
      - "docker-compose-plugin={{ docker_compose_version }}"
    state: present
    update_cache: yes    
    
- name: Add the user to the Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes