# 🚧 This is for only with fedora amd64 hosts 🚧
all:
  children:
    fedora-amd64-group:
      hosts:
        fedora-amd64:
          ansible_host: webserver-fedora.range.local
          ansible_python_interpreter: /usr/bin/python3
